- name: variables
  hosts: localhost
  vars: #variable declaration
    Course: "DevOps"
    Trainer: "Siva"
    Duration: "3 months"
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."